default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_db
  username: postgres
  password: <%= Rails.application.credentials.dig(:database, :password) %>

test:
  <<: *default
  database: blog_db_test
  username: postgres
  password: <%= Rails.application.credentials.dig(:database, :password) %>

production:
  <<: *default
  database: blog_db_production
  username: postgres
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  host: localhost
  port: 5432
