default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  host: localhost
  port: 5432
  database: blog_db

development:
  <<: *default

test:
  <<: *default
  database: blog_db_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
